backend:
  name: github
  repo: vstanyshevskyy/starist-na-radist

media_folder: static/assets
public_folder: "/assets"

collections:
- name: volunteers
  label: Волонтери
  folder: "content/volunteers"
  create: true
  fields:
    - name: "contentType"
      widget: "hidden"
      default: "volunteers"
    - {label: "Url", name: "path", widget: "string"}
    - {label: "Ім'я", name: "name", widget: "string"}
    - {label: "Підзаголовок", name: "subtitle", widget: "string", required: false}
    - {label: "Фото", name: "image", widget: "image", required: false}
    - {label: "Текст", name: "body", widget: "markdown"}
    - {label: "Instagram", name: "instagram", widget: "string", required: false}
    - {label: "FB", name: "facebook", widget: "string", required: false}
    - {label: "Meta Title", name: "metaTitle", widget: "string", required: false }
    - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
    - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
- name: settings
  label: Налаштування
  files:
    - label: "Проект в цифрах"
      name: "numbers"
      file: "content/settings/numbers.md"
      fields:
        - name: "contentType"
          widget: "hidden"
          default: "numbers_settings"
        - label: "Заголовок"
          name: "title"
          widget: "string"
          default: "Проект в цифрах"
        - label: "Блоки"
          name: "blocks"
          widget: "list"
          fields:
            - {label: Цифра, name: value, widget: string, default: ""}
            - {label: Текст, name: title, widget: string, default: ""}
    - label: "Футер"
      name: "footer"
      file: "content/settings/footer.md"
      fields:
        - name: "contentType"
          widget: "hidden"
          default: "footer_settings"
        - label: "Копірайт"
          name: "copyrightText"
          widget: "string"
    - label: "Контакти"
      name: "contacts"
      file: "content/settings/contacts.md"
      fields:
        - name: "contentType"
          widget: "hidden"
          default: "contacts_settings"
        - label: "Facebook"
          name: "facebook"
          widget: "string"
          default: "https://www.facebook.com/pg/staristNAradist"
        - label: "Instagram"
          name: "instagram"
          widget: "string"
          default: "https://www.instagram.com/pg/staristNAradist"
        - label: "YouTube"
          name: "youtube"
          widget: "string"
          default: "https://www.youtube.com/channel/UCydvBI5YmJPtRv5yzsQmIdA" 
        - label: "Адреса"
          name: "address"
          widget: "string"
          default: "Львів, вул. Медової Печери" 
        - label: "Телефон"
          name: "telephone"
          widget: "string"
          default: "+38 050 123-12-12" 
        - label: "Email"
          name: "email"
          widget: "string"
          default: "test@test.com" 
        - label: "Центр карти - lat"
          name: "mapCenterLat"
          widget: "number"
          valueType: "float"
          default: 49.825469
        - label: "Центр карти - lng"
          name: "mapCenterLng"
          widget: "number"
          valueType: "float"
          default: 24.068428
        - label: "Маркер на карті - lat"
          name: "mapMarkerLat"
          widget: "number"
          valueType: "float"
          default: 49.8231260
        - label: "Маркер на карті - lng"
          name: "mapMarkerLng"
          widget: "number"
          valueType: "float"
          default: 24.0887240
    - label: "Волонтери"
      name: "volunteers_settings"
      file: "content/settings/volunteers.md"
      fields:
        - name: "contentType"
          widget: "hidden"
          default: "volunteers_settings"
        - name: "homepageTitle"
          label: "Заголовок на головній"
          widget: "string"
          default: "Команда волонтерів"
        - name: "homepageCount"
          label: "Кількість волонтерів на головній"
          widget: "number"
          default: 4
        - name: "seeAllText"
          label: "Текст ссилки на головній"
          widget: "string"
          default: "Переглянути всіх"