backend:
  name: github
  repo: vstanyshevskyy/starist-na-radist

media_folder: static/assets

collections:
- name: settings
  label: Налаштування
  files:
    - label: "Проект в цифрах"
      name: "numbers"
      file: "content/settings/numbers.md"
      fields:
        - name: "contentType"
          widget: "hidden"
          default: "numbers_settings"
        - label: "Заголовок"
          name: "title"
          widget: "string"
          default: "Проект в цифрах"
        - label: "Блоки"
          name: "blocks"
          widget: "list"
          fields:
            - {label: Цифра, name: value, widget: string, default: ""}
            - {label: Текст, name: title, widget: string, default: ""}
    - label: "Футер"
      name: "footer"
      file: "content/settings/footer.md"
      fields:
        - name: "contentType"
          widget: "hidden"
          default: "footer_settings"
        - label: "Копірайт"
          name: "copyrightText"
          widget: "string"
    - label: "Контакти"
      name: "contacts"
      file: "content/settings/contacts.md"
      fields:
        - name: "contentType"
          widget: "hidden"
          default: "contacts_settings"
        - label: "Адреса"
          name: "address"
          widget: "string"
          default: "Львів, вул. Медової Печери" 
        - label: "Телефон"
          name: "telephone"
          widget: "string"
          default: "+38 050 123-12-12" 
        - label: "Email"
          name: "email"
          widget: "string"
          default: "test@test.com" 
        - label: "Центр карти - lat"
          name: "mapCenterLat"
          widget: "number"
          valueType: "float"
          default: 49.825469
        - label: "Центр карти - lng"
          name: "mapCenterLng"
          widget: "number"
          valueType: "float"
          default: 24.068428
        - label: "Маркер на карті - lat"
          name: "mapMarkerLat"
          widget: "number"
          valueType: "float"
          default: 49.8231260
        - label: "Маркер на карті - lng"
          name: "mapMarkerLng"
          widget: "number"
          valueType: "float"
          default: 24.0887240
            